### ISSUE TITLE
it cannot load class by ServiceLoader if set sharedUserId

### ISSUE THREAD

**Issue by ApertureF1** [Arrowyi/AutoConfig#2]
When an Android app has a shared UID (User ID), it can sometimes cause issues when using ServiceLoader.load to load classes. ServiceLoader relies on the context's class loader to load the specified service class, and when using a shared UID, the class loader may not have access to the necessary resources or dependencies

 try another method that is to explicitly specify the class loader to use when loading the service class:

val load = ServiceLoader.load(
ConfigRegister::class.java, ConfigRegister::class.java.classLoader
)

**Comment by Arrowyi** [comment]
fix with v1.0.0 release

**Comment by Arrowyi** [comment]
fix with v1.0.0 release
